### ISSUE TITLE
TimeoutError: Waiting for selector `#__next .btn-primary` failed

### ISSUE THREAD

**Issue by NuperSu** [RainEggplant/chatgpt-telegram-bot#5] opened 2023-02-02 12:30 UTC
I get this error when I try to run docker:
```
chatgpt-telegram-bot-app-1  | > chatgpt-telegram-bot@1.0.4 start /app
chatgpt-telegram-bot-app-1  | > node dist/index.js
chatgpt-telegram-bot-app-1  | 
chatgpt-telegram-bot-app-1  | TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
chatgpt-telegram-bot-app-1  |     at Timeout.<anonymous> (/app/node_modules/.pnpm/registry.npmmirror.com+puppeteer-core@19.6.3/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:65:32)
chatgpt-telegram-bot-app-1  |     at listOnTimeout (node:internal/timers:564:17)
chatgpt-telegram-bot-app-1  |     at process.processTimers (node:internal/timers:507:7)
chatgpt-telegram-bot-app-1  |  ELIFECYCLE  Command failed with exit code 1.
chatgpt-telegram-bot-app-1 exited with code 1
```
Tried rebuilding docker image but it didn't help.

**Comment by RainEggplant** [comment] 2023-02-02 14:49
This may be due to the fact that chatgpt is currently in high demand and the login page will not show at this time. Try again after a while and see if the problem persists.

**Comment by VectorZhao** [comment] 2023-02-04 05:11
```

> chatgpt-telegram-bot@1.0.5 start /app
> node dist/index.js

TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
    at Timeout.<anonymous> (/app/node_modules/.pnpm/registry.npmmirror.com+puppeteer-core@19.6.3/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:65:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
 ELIFECYCLE  Command failed with exit code 1.

> chatgpt-telegram-bot@1.0.5 start /app
> node dist/index.js

```
the same error for me, I tried again and again, but i can not fix it.
and
Is there any chance we can use a bot version that doesn't require a browser? Will the arm version of the docker image be released then.

**Comment by RainEggplant** [comment] 2023-02-04 06:49
I encountered this problem today. It seems that OpenAI is sometimes asking for a new cloudflare captcha before showing the "log in" / "sign up" page.
<img width="379" alt="cloudflare_captcha" src="https://user-images.githubusercontent.com/20147921/216752846-75364360-4ee6-4fe4-a1ab-777fc0bf159c.png">

Currently, you'll have to solve the captcha manually (if you're using xvfb, you'll need to connect to the virtual display first).

> Is there any chance we can use a bot version that doesn't require a browser?

After the v4 of [chatgpt api](https://github.com/transitive-bullshit/chatgpt-api/) becomes stable, I'll update the code and then we'll be able to use a lightweight solution (which requires an OpenAI API key and may not be free though).

> Will the arm version of the docker image be released then.

Currently it is not planned. You may search for some discussions [here](https://github.com/transitive-bullshit/chatgpt-api/issues).

**Comment by VectorZhao** [comment] 2023-02-04 08:33
> 
Thanks for you answers.
could i use Google reCaptcha to solve the captcha？

**Comment by RainEggplant** [comment] 2023-02-09 03:58
> could i use Google reCaptcha to solve the captcha？

I'm not sure what you mean. This captcha is from Cloudflare, not the Google reCAPTCHA.

**Comment by RainEggplant** [comment] 2023-02-19 11:56
Closed as the issue is related to the upstream API.

FYI, now you can use the unofficial API that comes with v2.1.0 to bypass CloudFlare without a browser.

**Closed by RainEggplant** 2023-02-19 11:56 UTC
